package com.puttysoftware.fantastlereboot.assets;

public enum GameEffectImage {
    ACTIONS_00, ACTIONS_01, ACTIONS_02, ACTIONS_03, ACTIONS_04, ACTIONS_05,
    ACTIONS_06, ACTIONS_07, ACTIONS_08, ACTIONS_09, ACTIONS_10, ACTIONS_11,
    ACTIONS_12, ACTIONS_13, ACTIONS_14, ACTIONS_15, ACTIONS_16, ACTIONS_17,
    ACTIONS_18, ACTIONS_19, BLIND, CLAIRVOYANT, CREATURE_ID, CREATURE_LEVEL,
    CREATURE_TEAM, DEFENSE, EXPERIENCE, FORTIFIED, GATHERING, HASTED, HEALTH,
    LEARNING, MAGIC, MELEE_ATTACK, MONEY, POISONED, POOR, RANGED_ATTACK,
    REGENERATING, RICH, SLOWED, SPEED, STRONG, VULNERABLE, WEAK, WITHERING,
    YEARNING, _NONE
}
