package com.puttysoftware.fantastlereboot.assets;

public enum MusicIndex {
  FINAL_WINDOW_BATTLE, FINAL_MAP_BATTLE, NORMAL_MAP_BATTLE, BOSS_MAP_BATTLE,
  NORMAL_WINDOW_BATTLE, BOSS_WINDOW_BATTLE, TITLE, DUNGEON, _DUNGEON_RANDOM_2,
  _DUNGEON_RANDOM_3, _DUNGEON_RANDOM_4, SHOP, _NONE
}
