package com.puttysoftware.fantastlereboot.assets;

public enum SoundIndex {
  ACTION_FAILED, ALERT, ARROW_DIE, ARROW_HIT, ARROW_SHOOT, AXE_CRIT, AXE_HIT,
  BARRIER, BITE, BLOCKED, BOLT, BOSS_DIE, BREAK, BUBBLE, BUFF_1, BUFF_2, BUFF_3,
  BUFF_4, BUFF_5, BUTTON, CHANGE, CLAW, CLICK, CLUB_CRIT, CLUB_HIT, CONFUSED,
  COOL_OFF, CRACK, CREATE, CRITICAL, CRUSH, DARK_STONE, DARKNESS, DEATH,
  DEBUFF_1, DEBUFF_2, DEBUFF_3, DEBUFF_4, DEBUFF_5, DESTROY, DISPEL, DIZZY,
  DOOR_CLOSES, DOOR_OPENS, DOWN, DRAIN, DRAW_SWORD, DRUNK, EASIER, EQUIP,
  ERA_CHANGE, ERAS_ENABLED, ERROR, EXPLODE, FAILED, FALLING, FATAL, FINISH,
  FIREBALL, FOCUS, FREEZE, FUMBLE, GAME_OVER, GENERATE, GET_READY, GRAB,
  HAMMER_CRIT, HAMMER_HIT, HARDER, HEAL, HIGH_SCORE, HURT, IDENTIFY, INTO,
  INTO_PIT, KABOOM, KICK, LASER, LEVEL_UP, LIGHT, LIGHT_FUSE, LIGHT_STONE, LOGO,
  LOSE, LOW_HEALTH, MACE_CRIT, MACE_HIT, MAGNET, MELT, MISSED, MISSILE,
  MONSTER_ACTION, MONSTER_COUNTER, MONSTER_HIT, MONSTER_SPELL, MOON_STONE,
  NEXT_ROUND, ON_WHO, OOF, OUT, OW, PARALYSIS, PARTY_ACTION, PARTY_COUNTER,
  PARTY_DEAD, PARTY_HIT, PARTY_SPELL, PICK_LOCK, PLAYER_UP, POP, PULL, PUNCH,
  PUSH, PUSH_PULL_FAILED, RETURN, ROTATED, RUN, SHOCKED, SHOP, SINK, SLICE,
  SLIDE, SLIME, SONAR, SPARK, SPEAR_CRIT, SPEAR_HIT, SPECIAL, SPINNER, SPRING,
  STAR_STONE, SUMMON, SUN_STONE, SWORD_CRIT, SWORD_HIT, TELEPORT, TRANSACT,
  TRAP, U_TURNED, UNLOCK, UP, USE_FAILED, VICTORY, WALK, WALK_2, WALK_3, WALK_4,
  WALK_5, WALK_6, WALK_FAILED, WALK_ICE, WALK_LAVA, WALK_SLIME, WALK_WATER,
  WAND, WEAKNESS, WEAPON_TOO_WEAK, WEAR_OFF, WIN_GAME, WRONG, ZAP, _NONE
}
